data:
  root_dir: '/media/talmacsi/48a93eb4-f27d-48ec-9f74-64e475c3b6ff/Downloads/celeba'
  image_dir: 'images'
  attributes_file: 'list_attr_celeba.txt'
  selected_attrs:
    -2: Old
    -1: Female
    8: Black_Hair
    9: Blond_Hair
    11: Brown_Hair
    20: Male
    39: Young
  crop_size: 178
  image_size : 128

model:
  c_dim : 7
  g_conv_dim: 64
  d_conv_dim: 64
  g_repeat_num: 6
  d_repeat_num: 6

training:
  device: 'cuda'
  batch_size: 4
  random_seed: 42
  epochs: 200
  g_lr: 0.0001
  d_lr: 0.0001
  n_critics: 5
  beta1: 0.5
  beta2: 0.999
  lambda_rec: 10
  lambda_cls: 1
  lambda_gp: 10
  num_workers: 0
  log_interval: 10 # iteration
  save_interval: 10 # epoch
  sample_interval: 1000000000 # epoch
  resume_training: False
  resume_checkpoint: ''
  sample_size: 2
  num_grid_rows : 1


folders:
  output: 'outputs'
  weights: 'weights'
  logs: 'logs'
  checkpoints: 'outputs/checkpoints'
  samples: 'outputs/samples'